language: python
python:
  - 3.6
before_install:
  - echo -e "machine github.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
  - git lfs pull
  - git lfs fetch --all
install:
  - pip install awscli boto3 requests
branches:
  only:
    - release
script:
  - git clone https://github.com/drewcassidy/build-deploy.git
  - cd build-deploy
  - git checkout master
  - cd ..
  - pytest -s --testpath "GameData/" build-deploy/src/tests/  # run the deploy tests
  - python build-deploy/src/package.py --f ".mod_data.yml"  # Build package
before_deploy:
  - python build-deploy/src/stage.py --f ".mod_data.yml" # Run the staging script
deploy:
  - provider: script
    script: python build-deploy/src/deploy.py --f ".mod_data.yml" # Deploy package to spacedock, curse, github
    skip_cleanup: true
    on:
      branch: release